services:
  app:
    build:
      context: ./docker/php/
      args:
        - USER_ID
        - GROUP_ID
    working_dir: /var/www/app
    volumes: 
      - .:/var/www/app
    ports:
      - 8000:8000
    networks:
      - default
      - common
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./docker/mariadb/initdb:/docker-entrypoint-initdb.d
      - dom-db:/var/lib/mysql
    ports:
      - 3307:3306
networks:
  common:
    external: true
    name: common-network
volumes:
  dom-db: